apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:S8nOl9CpJ8sKrpV92HGwJBnbcgCv/Kro3unRNk5OUXeGvgHg,iv:ViTrLx5XBpGRwCWYQEV9N2WgP1vel0bx+JIuEDtqNrU=,tag:Wsjn7i4gmZf0xt5if20qcQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:B6/RzVHuyrmH8Nv5mwx5eGMMR6UKT+3aA8TZsjMtAjGl1Z7fCYmBC2m2WYFEyqxMmvJKyXK9WcGzh+WqI94Igy35VYWb7idA3joedZp49QMyv8ZbOAMQ+ygjuYWGMM4s0dstMheUFtQNXsDKLe174U+vKG2BMENzJgtLO2VRq0R4MODZakKu/Ck+0uefsM+crG1qUUquiqM7bJL3RHYUoeg7+ZS11B05kWJsFeiKzA==,iv:9UA55pXXa1bsOBoKbc9LSF8vIsIC1o38DSc0YvEuzWw=,tag:RjTOdbC/RTB4STupe5bo7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8u26jxxx3ls68u6sy03udtex6wzen0vqx28qesg95752n9uksfqv947sm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUUM0TllXVHdqVmRwOVg4
            MkVaNXlLU21sTWNoRTc1TjVBYWc0UTBicVQ4Cmd0ZEsrT2VuYTZ4cW93SHhiWnpV
            U2VYT3RqQ09ZcDIxRVdtUmVjdkFpRHcKLS0tIHdKeTk3TXZHc05ZWExzVzNOUm10
            MXVmVFVjdm43c1pXRThScU1QSmVBSjQK1MNS9Dfeb5g3Qshst14OZcXSuTnp1yc0
            jpKiltIvrLPEheDsacNOi4BjmCYbEME1j9Hvq3f47yNlAQ+hVRxlaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T22:40:50Z"
    mac: ENC[AES256_GCM,data:HUPOMi+cchjo+ky4y2SPDEFQdnBvp+ku0CndblMFrfE+GHZzU9OWu4OVOv45HayGm2jcIq8WOX1ulLQUkJa5slzrv3B05Gp0+trcL9CcdBLY6aIKJHhqHroMTnjEcHVRcC0TK2mH6o2sJkigbbnLOW9++pVzJYelNMNYQ94kzEU=,iv:Taw0+gAYyqr3DJDU4s12xKJ1lHRs5WpL4/4P70ybwxQ=,tag:04yXegv745nEUY0zsljJoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
