apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:G2jH26n/nyNS1WcPCDI8ZPmrxdeHg/QNDOXt4fPj4Pat4VOxZMON8g==,iv:EyPIIfAxWaWOJ+3i8didc02z8kOve05Ucn8tucyQqLM=,tag:NqWY57z63RZxLv6GuLO2hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pke2vgr7n2fxj77wcfl82pypnndrn2z70xx26gcgjdft4g4krgeqqdv6hk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTVhlamVYKzNqMUlIdkxO
            WGdlL3JYRmFDeW1MZlEyVExmMzdMOWNDNFJFCm5NdjdHWVdlQk1hUmFuRXB5Qnpi
            bzFiVVhWaGJKdDJITGxGRlBYZnptSWMKLS0tIGFvZkV4aXJzMDY3NGc5N2MxTHZP
            dXczdFlSK0RrWlMvd2JPbjEyOU0xYkkKtY0OWchMmpNtmTpLm72GhQNLCQzZ/OCK
            JakYYfJOYX6BTHbDQSkGynd1M4E1/Kc5xCEHvXxSX0sF4JHwJGcttQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T22:48:21Z"
    mac: ENC[AES256_GCM,data:rQvH8ZsAa9TwtkYAxoPK9ztn0SkSFkI9qv7TLIB9cMV235DZEbsDsBTkEyIxi6wV81XRKjpC/1qi8CIyqxoZHYxERwvgyw7gtz1Z4+cTyfo/Y+iw2LXNm1FZSWlUZkox2cubKu+T8+qVhm0wr2kGl/56diphBzJYaClWdZgJyo8=,iv:8jbnFCO+sXcy5OAQkbycIGQOCyBz1O3hV+xCgd8TycY=,tag:7aG7R7i8MBnLdW9kjhz4QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
