apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:xi7RF8FxAkGj22zCnqeZHjzwF3VqPmiTEwb++bamp/TdRfVzYe7rSQ==,iv:fXSuF6lR/wLfUtuVO9z8G5fMSLTJI4A6QjDK4Zc+4W8=,tag:KJm+7QocdZc8Rf3H4hxPaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8u26jxxx3ls68u6sy03udtex6wzen0vqx28qesg95752n9uksfqv947sm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSURJZXBuaGFTNTM4TXJC
            UzdOb2hzQktWRkhTTlMzZ1orNkl0U3RsTWlFCnk3V2ZtWVJrbE1GVkR6MVdJdWN4
            eDhtZFhoWW5jQlZ6bFI4NnpnSmhlbk0KLS0tIDdPaGdVb09MRnlWZGVZdkU2OHJX
            UzNkb2ljU1FFRzRxK1NnaTBPdWtaN3cK9Cr/y7l3GtIHJSHqXWvNjIVKrRGp9vO4
            DbQ9RB2lKobb0LtK/hyW46x7gfZVvtL5Smy5OHXbZNYOy3+BA71oSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T22:40:50Z"
    mac: ENC[AES256_GCM,data:09XOpnzj5TMIz/+d1JdY4pmwcHK2h/XQnLmrsEe99izuYBSgggfZE7ti+iwMJJTA0QYVNMiRBU42xXe+FepE6Q8zOHNhmWroe6whUsDh4eRYODlNjzIpPzJuxC2TIOM6/HuznF1vwWu2OQr8PE1giHDh1XvtzGXu2hz/plGc12Y=,iv:27VbNuUdhX7tIiz4cbbF19u1gJ+yoamZCV4ueWBTB6I=,tag:jOR6wWpu3DFmA+zbJYRsJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
