apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:v/x52lLzwiuypau0IL26HMpyc21JkVjw988cg/8X3nXvvF2Ieq6JHA==,iv:chod0nHAVtfGJKtaf+/kZj9jpsgM0eo3Rmn0pMC1GuA=,tag:MMV7XqV4m83BXVcZv1XRXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pke2vgr7n2fxj77wcfl82pypnndrn2z70xx26gcgjdft4g4krgeqqdv6hk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ODgzWmxXdWpVam15UXlF
            OVhBTFdYM04wZS9rUXA2M0wzZEZ3MTE2ZzJNCkkybFF2dzVhRTVKZ3VKZ0lXS0hL
            Z0U0WUNqSzFrLytVM2NTQkx0alZjNU0KLS0tIGE3eXlIbGtIS1FHc0NTdEk3K0I5
            Q3d5L0dRVklEdmdZTURYUHlTMUU5dHMKchYXjUZ+Tp8iJ0UCILTdocv8/Qy+2nsC
            wA4lspBe7ecB3BBKZ6JeER03kFLqmOF6iJVDLkLJ6HxKqVu2kbfdsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T22:48:21Z"
    mac: ENC[AES256_GCM,data:sIg4KnHJ/D4LQKJWjo5vkC3k7pCLd/8BMV8lmbHMkySzL7+/ufk9ygv7zKOIDJvl81RdPosFW8IFOdgB83PNe+qXdPyfSetSnqmKQuS4IP3XRTYiQ4ewccPJGn9j81y2RLHjqXNiU0I40AEz16619WK4KU+BkViN6m1r0og5i1c=,iv:3IgXFIvodlZd3YVfqu0ULM9B4BOBclHLZ7+eVBEn+KU=,tag:pytd6b2qTKeC7AlH4h2qBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
